#!/bin/sh

# This shell script gets and unpacks the latest fontforge AppImage

# source buildScripts/reSourceVersionEnvs
. buildScripts/reSourceVersionEnvs

echo ""
echo "-------------------------------------------------------------------"
echo "GETTING FontForge sources (using wget)"
echo "  (FONTFORGE_VERSION: [$FONTFORGE_VERSION])"
echo "-------------------------------------------------------------------"
echo ""

set -ev

FONTFORGE_SRC=$FONTFORGE_VERSION.tar.gz

rm -rf $FONTFORGE_SRC
rm -rf fontforge

wget https://github.com/fontforge/fontforge/archive/$FONTFORGE_SRC

tar xvf $FONTFORGE_SRC

mv fontforge-$FONTFORGE_VERSION fontforge

# Temporarily remove problematic translations to allow build to pass
echo "Patching FontForge LINGUAS file to remove fr and it translations..."
sed -i '/^fr$/d' fontforge/po/LINGUAS
sed -i '/^it$/d' fontforge/po/LINGUAS
echo "Done patching LINGUAS file."
